osx_image: xcode8.3
language: objective-c
xcode_scheme: SampleApp

env:
  global:
  - secure: dNIrYP+y8I0LYVFthQTSFro6KuRTwKqgJv001XllHFfZlp8WBcOPdt1tjho0DWJwaVisdJCO1tLzP6KCgGfhFPuxZfaCriTluuAYRSnlx8IF1c/1rbdlJSSoqJHkx2s62Qu8hz3Xd96PPBnR4E8M8n5rZfCesnN46ltt2tJnUeWVdXYogwhSWiAqPGcYdltW5J/Dzuyaayx+J1XHyb3WWdvxsfcBulLnda/gkDxKKo7Kd3Ag8uvdozqGVZ8w3MxSybUQMNMvBK8VFcdceihELMxtuU5/o6OFAqsRVjY5W26soV1RtMqbZrlcBATQbFKaPKTcD9NqAzLj9cwSiEnaeXBUTLl3xKx7FGiVDpj1BEEyAJFbo6th6oW6msymik/SeNHfeXkw3HgkAtnu/PdYTE7tgz8RGRr/WisqvpR6vO5vZY/RakJ2jkzT+KgLNvRjKahi94DsvtKo+ZcxnPI6xfHodN88bAndap4pXMU98u4zRwAzdXd5kOtfPDkF26kuclLCA7xta+9SkgI+syJz9GsITKCZBxZK4iXyJNmhyeqmlKYV/SENTnbhlrXvuSCb1Jz9pR0vS51Q1xv+1TFfeyzhgTKktyWlFym8JNHDJt3iBGLGhq609XiQCHDBN+3SD9eWUJfJ4iTfvD5RTGzTdclK8HuqX62zE/2dKFeQukw=
  - secure: UcgA/H9LoC3dJKq0a+d6AjJpyq3OJ/g2Z5C9Yt6mTkqEYw4v9EdkOCgucsXXvXRdDJRl5L5T+ViIOVJW/uZpK2LQEG+nKm3zmP/abz8czagevwt9/G4o+SqSEbC5VN/4bOS9zhWFNn/7PsrKqJtu9LWSrjgeWpZ2AuC8fRz8/VcP9ojgjY589YtqstN7ptTkbMxTENvK6wQLrf7YpFDfMbImD49+tNY9svtnCUhzONmKc36+D7tjXaWfV61fPVnIDhmwNZ0kIvENYfB4oH6LjQXI2mWoQrC0PfAVTP/WcP9MLfPkANZWafxdOcUvUp0YcwiV4YWTNI07UNvymK50Kc+ooano102QrnCCzo9J2Y217NknBYZ9VqFIEtxF8qnLN0rq9cwkeaiQ/+XDMXEH9R0bOYZ+tINjXQ5rDDFHAhvJy6oyC+Ost+Qho0UPGW0GCAclJhrilXT/raKwCVDyjarjgTXS5X2rVTRcw3ROIjPEnl8RXbUgqLsbuw/44zL+vTZhYHOM49ULstmYQRvZ+zt1LjPGwXI8ecv4E46uT+MI+q+3+9OVerDSy/oSFdwSRVWumIqbfGqMh9fxdy56UBuHgqF4BNGE5CMRca+zHbsYdjnU/y5W/DqhIJmHLB+MChSVZaNnbeRNN50dFLqypNprv9FASIIiyX+mklxeODA=

before_install:
  - openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profiles/AdHocSampleAppDist.mobileprovision.enc -d -a -out scripts/profiles/AdHocSampleAppDist.mobileprovision
  - openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.cer.enc -d -a -out scripts/certs/dist.cer
  - openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.p12.enc -d -a -out scripts/certs/dist.p12
  - mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
  - cp "./scripts/profiles/AdHocSampleAppDist.mobileprovision" ~/Library/MobileDevice/Provisioning\ Profiles/

script: fastlane test
