osx_image: xcode8.3
language: objective-c
xcode_project: SampleApp.xcodeproj # path to your xcodeproj folder
xcode_scheme: SampleApp

before_install:
  - gem update --system
  - gem install fastlane --no-rdoc --no-ri --no-document --quiet


script: fastlane test
